# Financial Data Filtering For Practice

In [1]:
import pandas as pd 

data = pd.read_csv("beginner_pandas_sales.csv")

In [2]:
df = pd.DataFrame(data)

In [3]:
# print(df)
print(df.head())
# print(df.tail())
# print(df["year"])
# print(df.shape)
# print(df.info)
# print(df.dtypes)

   order_id customer_name     city     product  quantity  unit_price  \
0      1001         Aarav    Delhi      Laptop         1       55000
1      1002         Priya   Mumbai  Headphones         2        1500
2      1003         Rahul  Chennai    Keyboard         1        2200
3      1004         Sneha     Pune       Mouse         3         600
4      1005          Amit    Delhi     Monitor         1       12000

   order_date
0  2026-01-03
1  2026-01-04
2  2026-01-05
3  2026-01-06
4  2026-01-07

## Filtering the Data

In [4]:
df[["order_id", "customer_name","city","product","quantity","unit_price","order_date"]]

# df.columns

,order_id,customer_name,city,product,quantity,unit_price,order_date
0,1001,Aarav,Delhi,Laptop,1,55000,2026-01-03
1,1002,Priya,Mumbai,Headphones,2,1500,2026-01-04
2,1003,Rahul,Chennai,Keyboard,1,2200,2026-01-05
3,1004,Sneha,Pune,Mouse,3,600,2026-01-06
4,1005,Amit,Delhi,Monitor,1,12000,2026-01-07
5,1006,Neha,Jaipur,Headphones,1,1800,2026-01-08
6,1007,Vikram,Mumbai,Laptop,1,62000,2026-01-09
7,1008,Ananya,Chennai,Mouse,2,650,2026-01-10
8,1009,Rohan,Pune,Keyboard,2,2000,2026-01-11
9,1010,Kavya,Delhi,Headphones,1,1500,2026-01-12
10,1011,Ishaan,Jaipur,Monitor,2,11500,2026-01-13
11,1012,Meera,Mumbai,Mouse,1,700,2026-01-14
12,1013,Arjun,Chennai,Laptop,1,58000,2026-01-15
13,1014,Pooja,Pune,Headphones,3,1600,2026-01-16
14,1015,Karan,Delhi,Keyboard,1,2400,2026-01-17
15,1016,Diya,Jaipur,Mouse,4,550,2026-01-18
16,1017,Manish,Mumbai,Monitor,1,12500,2026-01-19
17,1018,Tanya,Chennai,Headphones,2,1700,2026-01-20
18,1019,Aditya,Pune,Laptop,1,60000,2026-01-21
19,1020,Riya,Delhi,Mouse,2,600,2026-01-22
20,1021,Dev,Jaipur,Keyboard,2,2100,2026-01-23
21,1022,Simran,Mumbai,Headphones,1,1900,2026-01-24
22,1023,Yash,Chennai,Monitor,1,11800,2026-01-25
23,1024,Nisha,Pune,Mouse,3,650,2026-01-26
24,1025,Kabir,Delhi,Laptop,1,57000,2026-01-27
25,1026,Aditi,Jaipur,Headphones,2,1550,2026-01-28
26,1027,Sahil,Mumbai,Keyboard,1,2300,2026-01-29
27,1028,Ira,Chennai,Mouse,1,700,2026-01-30
28,1029,Varun,Pune,Monitor,1,12200,2026-01-31
29,1030,Maya,Delhi,Headphones,2,1650,2026-02-01

In [5]:
df.loc[3]

order_id               1004
customer_name         Sneha
city                   Pune
product               Mouse
quantity                  3
unit_price              600
order_date       2026-01-06
Name: 3, dtype: object

### Selecting Rows and Columns

In [6]:
df.loc[1,"customer_name"]

'Priya'

In [7]:
df.iloc[1,2]

'Mumbai'

In [8]:
df.loc[0:2, ["customer_name","city"]]

  customer_name     city
0         Aarav    Delhi
1         Priya   Mumbai
2         Rahul  Chennai

In [9]:
df.at[7,"customer_name"]

'Ananya'

## Filtering with Conditions

Here I'm going to do the filtering of the data with conditions

In [10]:
df[df["quantity"]>1]

,order_id,customer_name,city,product,quantity,unit_price,order_date
1,1002,Priya,Mumbai,Headphones,2,1500,2026-01-04
3,1004,Sneha,Pune,Mouse,3,600,2026-01-06
7,1008,Ananya,Chennai,Mouse,2,650,2026-01-10
8,1009,Rohan,Pune,Keyboard,2,2000,2026-01-11
10,1011,Ishaan,Jaipur,Monitor,2,11500,2026-01-13
13,1014,Pooja,Pune,Headphones,3,1600,2026-01-16
15,1016,Diya,Jaipur,Mouse,4,550,2026-01-18
17,1018,Tanya,Chennai,Headphones,2,1700,2026-01-20
19,1020,Riya,Delhi,Mouse,2,600,2026-01-22
20,1021,Dev,Jaipur,Keyboard,2,2100,2026-01-23
23,1024,Nisha,Pune,Mouse,3,650,2026-01-26
25,1026,Aditi,Jaipur,Headphones,2,1550,2026-01-28
29,1030,Maya,Delhi,Headphones,2,1650,2026-02-01

## Multiple Conditions And and OR

In [11]:
df[(df["quantity"]>1) & (df["city"]=="Pune")]

    order_id customer_name  city     product  quantity  unit_price  order_date
3       1004         Sneha  Pune       Mouse         3         600  2026-01-06
8       1009         Rohan  Pune    Keyboard         2        2000  2026-01-11
13      1014         Pooja  Pune  Headphones         3        1600  2026-01-16
23      1024         Nisha  Pune       Mouse         3         650  2026-01-26

In [12]:
df[(df["quantity"]>2) | (df["city"]=="Pune")]

,order_id,customer_name,city,product,quantity,unit_price,order_date
3,1004,Sneha,Pune,Mouse,3,600,2026-01-06
8,1009,Rohan,Pune,Keyboard,2,2000,2026-01-11
13,1014,Pooja,Pune,Headphones,3,1600,2026-01-16
15,1016,Diya,Jaipur,Mouse,4,550,2026-01-18
18,1019,Aditya,Pune,Laptop,1,60000,2026-01-21
23,1024,Nisha,Pune,Mouse,3,650,2026-01-26
28,1029,Varun,Pune,Monitor,1,12200,2026-01-31

## Quering with .Query

The .query() method in pandas lets you filter DataFrame rows using a string
expression — it’s a more readable and often more concise alternative to using
boolean indexing.

In [13]:
df.query('unit_price > 800 and city=="Pune"') # This will give the query which will be like the Readable Statement.

    order_id customer_name  city     product  quantity  unit_price  order_date
8       1009         Rohan  Pune    Keyboard         2        2000  2026-01-11
13      1014         Pooja  Pune  Headphones         3        1600  2026-01-16
18      1019        Aditya  Pune      Laptop         1       60000  2026-01-21
28      1029         Varun  Pune     Monitor         1       12200  2026-01-31

## Dynamic Columns Names

In [14]:
col = "unit_price"

df.query(f"{col} > 10000")

    order_id customer_name     city  product  quantity  unit_price  order_date
0       1001         Aarav    Delhi   Laptop         1       55000  2026-01-03
4       1005          Amit    Delhi  Monitor         1       12000  2026-01-07
6       1007        Vikram   Mumbai   Laptop         1       62000  2026-01-09
10      1011        Ishaan   Jaipur  Monitor         2       11500  2026-01-13
12      1013         Arjun  Chennai   Laptop         1       58000  2026-01-15
16      1017        Manish   Mumbai  Monitor         1       12500  2026-01-19
18      1019        Aditya     Pune   Laptop         1       60000  2026-01-21
22      1023          Yash  Chennai  Monitor         1       11800  2026-01-25
24      1025         Kabir    Delhi   Laptop         1       57000  2026-01-27
28      1029         Varun     Pune  Monitor         1       12200  2026-01-31

In [15]:
df.query("customer_name == 'Amit'")

   order_id customer_name   city  product  quantity  unit_price  order_date
4      1005          Amit  Delhi  Monitor         1       12000  2026-01-07

In [16]:
product_price = 900
df.query("unit_price > @product_price")

,order_id,customer_name,city,product,quantity,unit_price,order_date
0,1001,Aarav,Delhi,Laptop,1,55000,2026-01-03
1,1002,Priya,Mumbai,Headphones,2,1500,2026-01-04
2,1003,Rahul,Chennai,Keyboard,1,2200,2026-01-05
4,1005,Amit,Delhi,Monitor,1,12000,2026-01-07
5,1006,Neha,Jaipur,Headphones,1,1800,2026-01-08
6,1007,Vikram,Mumbai,Laptop,1,62000,2026-01-09
8,1009,Rohan,Pune,Keyboard,2,2000,2026-01-11
9,1010,Kavya,Delhi,Headphones,1,1500,2026-01-12
10,1011,Ishaan,Jaipur,Monitor,2,11500,2026-01-13
12,1013,Arjun,Chennai,Laptop,1,58000,2026-01-15
13,1014,Pooja,Pune,Headphones,3,1600,2026-01-16
14,1015,Karan,Delhi,Keyboard,1,2400,2026-01-17
16,1017,Manish,Mumbai,Monitor,1,12500,2026-01-19
17,1018,Tanya,Chennai,Headphones,2,1700,2026-01-20
18,1019,Aditya,Pune,Laptop,1,60000,2026-01-21
20,1021,Dev,Jaipur,Keyboard,2,2100,2026-01-23
21,1022,Simran,Mumbai,Headphones,1,1900,2026-01-24
22,1023,Yash,Chennai,Monitor,1,11800,2026-01-25
24,1025,Kabir,Delhi,Laptop,1,57000,2026-01-27
25,1026,Aditi,Jaipur,Headphones,2,1550,2026-01-28
26,1027,Sahil,Mumbai,Keyboard,1,2300,2026-01-29
28,1029,Varun,Pune,Monitor,1,12200,2026-01-31
29,1030,Maya,Delhi,Headphones,2,1650,2026-02-01